theme = "github_light"

[editor]
gutters = ["diagnostics", "diff"]
bufferline = "always"
default-yank-register = "+"

[editor.file-picker]
hidden = false
follow-symlinks = false

[editor.soft-wrap]
enable = true
